version: "3.9"
networks:
  lambda_bridge:
    external: false
    name: lambda_bridge
services:

  localstack:
    image: localstack/localstack:${LOCAL_STACK}
    environment:
      - SERVICES=${SERVICES-s3,sqs,sns,iam,lambda,cloudformation, cloudwatch}
      - HOSTNAME=${HOSTNAME-localhost}
      - HOSTNAME_EXTERNAL=${HOSTNAME_EXTERNAL-localhost}
      - DEFAULT_REGION=${DEFAULT_REGION-eu-west-1}
      - DEBUG=${DEBUG-1}
    ports:
      - 4566:4566
    networks:
      - lambda_bridge

  aws-mock:
    container_name: aws-cli-docker-${REPOSITORY}:${VERSION}
    build:
      context: ./infrastructure
      dockerfile: Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: none
      AWS_SECRET_ACCESS_KEY: none
      AWS_REGION: ${AWS_REGION-eu-west-1}
      SERVICENAME: ${REPOSITORY}
      ENVIRONMENT: docker
    networks:
      - lambda_bridge
    depends_on:
      - localstack