version: '2'

services:
  unittest:
    build:
      context: ./tests/unittests
      dockerfile: Dockerfile
      args:
        - BAMBORA_PYPI_PASSWORD
        - BAMBORA_PYPI_USERNAME
    image: unittests:${VERSION}

  unittest-watch:
    build:
      context: ./tests/unittests
      dockerfile: Dockerfile
      args:
        - BAMBORA_PYPI_PASSWORD
        - BAMBORA_PYPI_USERNAME
    entrypoint: ptw
    command: --ext=py,feature --ignore=/.cache/** --config /usr/unittests/pytest.cfg -p
    volumes:
      - ./app:/urs/app
      - './tests/unittests/:/usr/unittests/'

  systemtests-base:
    build:
      context: ./tests/systemtests
      dockerfile: Dockerfile
      args:
        - BAMBORA_PYPI_PASSWORD
        - BAMBORA_PYPI_USERNAME
    image: app-frame-systemtests:${VERSION}
    environment:
      S3_HOST: aws-mock:3000
      PYTHONDONTWRITEBYTECODE: '1'
    volumes:
      - ./tools/awsmock-credentials:/root/.aws/credentials

  systemtests:
    extends:
      service: systemtests-base
      file: docker-compose.test.yml
    volumes:
      - './tools/awsmock-credentials:/root/.aws/credentials'
    depends_on:
      - provisioner

  systemtests-watch:
    extends:
      service: systemtests-base
      file: docker-compose.test.yml
    entrypoint: ptw
    command: --ext=py,feature --ignore=/.cache/** --config pytest.cfg -p
    volumes:
      - './tools/awsmock-credentials:/root/.aws/credentials'
      - './tests/systemtests/:/usr/systemtests/'
      - './app/:/usr/app/'
    depends_on:
      - provisioner
