version: '2'

services:

  unittests-base:
    image: unittests-bi-framework:${VERSION}
    build:
      context: tests/unittests
      dockerfile: Dockerfile
      args:
        PYPI_USERNAME: ${PYPI_USERNAME}
        PYPI_PASSWORD: ${PYPI_PASSWORD}
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      AWS_REGION: ${AWS_REGION}
      ENVIRONMENT: docker
      VERSION: ${VERSION}
      AWS_REGION: ${AWS_REGION}
      APP_LOG_STYLE: text
      APP_LOGGING_HANDLER: CONSOLE
      APP_NAME: bi-framework
      APP_COMPONENT: data_integration
      INPUT_BUCKET: bi-framework-docker-eu-west-1
      PACKAGE_NAME: ${PACKAGE_NAME}
    volumes:
      - ./tools/awsmock-credentials:/root/.aws/credentials
      - ./packages:/packages
      - ./handlers:/tmp/handlers

  unittests:
    extends:
      service: unittests-base
      file: docker-compose.test.yaml

  unittests-watch:
    extends:
      service: unittests-base
      file: docker-compose.test.yaml
    environment:
      EXEC_BEFORE: export PYTHONPATH=$$PYTHONPATH:/tmp/handlers
    command: ptw --ext=py,feature --ignore=/.cache/** --config pytest.cfg -p --pdb
    volumes:
      - ./tests/unittests:/unittests
      - ./handlers:/tmp/handlers

  systemtests-base:
    image: systemtests-bi-framework:${VERSION}
    build:
      context: tests/systemtests
      dockerfile: Dockerfile
      args:
        PYPI_USERNAME: ${PYPI_USERNAME}
        PYPI_PASSWORD: ${PYPI_PASSWORD}
    environment:
      S3_HOST: aws-mock:3000
      PYTHONDONTWRITEBYTECODE: 1
      AWS_REGION: ${AWS_REGION}
      INPUT_BUCKET: bi-framework-data-lake-docker-eu-west-1
    volumes:
      - ./tools/awsmock-credentials:/root/.aws/credentials

  systemtests:
    extends:
      service: systemtests-base
      file: docker-compose.test.yaml
    depends_on:
      - lambdaserver

  systemtests-watch:
    extends:
      service: systemtests-base
      file: docker-compose.test.yaml
    entrypoint: ptw
    command: --ext=py,feature --ignore=/.cache/** --config pytest.cfg -p
    volumes:
      - ./tests/systemtests:/systemtests
    links:
      - lambdaserver-watch:lambdaserver
    depends_on:
      - lambdaserver-watch
