version: '3.8'

services:

  unittests:
    image: unittests-bi-framework:${VERSION}
    build:
      context: tests/unittests
      dockerfile: Dockerfile
      args:
        PYPI_USERNAME: ${PYPI_USERNAME}
        PYPI_PASSWORD: ${PYPI_PASSWORD}
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      AWS_REGION: ${AWS_REGION}
      ENVIRONMENT: docker
      VERSION: ${VERSION}
      AWS_REGION: ${AWS_REGION}
      APP_LOG_STYLE: text
      APP_LOGGING_HANDLER: CONSOLE
      APP_NAME: bi-framework
      APP_COMPONENT: data_integration
      INPUT_BUCKET: bi-framework-docker-eu-west-1
      PACKAGE_NAME: ${PACKAGE_NAME}
    volumes:
      - ./tools/awsmock-credentials:/root/.aws/credentials
      - ./packages:/packages
      - ./handlers:/app/src

  unittests-watch:
    build:
      context: tests/unittests
      dockerfile: Dockerfile
    environment:
      EXEC_BEFORE: export PYTHONPATH=$$PYTHONPATH:/app/src
    entrypoint: ptw
    command: --ext=py,feature --ignore=/.cache/** --config pytest.cfg -p --pdb
    volumes:
      - ./tests/unittests:/unittests
      - ./handlers:/app/src

  systemtests:
    image: systemtests-bi-framework:${VERSION}
    build:
      context: tests/systemtests
      dockerfile: Dockerfile
      args:
        PYPI_USERNAME: ${PYPI_USERNAME}
        PYPI_PASSWORD: ${PYPI_PASSWORD}
    networks:
      - internal
    environment:
      S3_HOST: aws-mock:3000
      PYTHONDONTWRITEBYTECODE: 1
      AWS_REGION: ${AWS_REGION}
      INPUT_BUCKET: bi-framework-data-lake-docker-eu-west-1
    depends_on:
      - lambdaserver

  systemtests-watch:
    build:
      context: tests/systemtests
      dockerfile: Dockerfile
    networks:
      - internal
    entrypoint: ptw
    command: --ext=py,feature --ignore=/.cache/** --config pytest.cfg -p
    volumes:
      - ./tests/systemtests:/systemtests
      - ./tools/awsmock-credentials:/root/.aws/credentials
    links:
      - lambdaserver-watch:lambdaserver
    depends_on:
      - lambdaserver-watch


networks:
  internal:
    driver: bridge
