version: "2"

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    image: app-framework

  provisioner:
    image: akino1976/aws-local-provisioner
    environment:
      S3_HOST: aws-mock:3000
      AWS_LOCAL_TEMPLATE: |
        version: '1.0'
        resources:
          storage_bucket:
            type: bucket
            name: app-uploads
    depends_on:
      - aws-mock

  aws-mock:
    image: localstack/localstack:0.8.6
    environment:
      DEFAULT_REGION: eu-west-1
      SERVICES: s3:3000
      FORCE_NONINTERACTIVE: 'true'
      HOSTNAME: aws-mock
      HOSTNAME_EXTERNAL: aws-mock
      DEBUG: 0
