AWSTemplateFormatVersion: '2010-09-09'

Description: Business Intelligence persistence infrastructure

Parameters:

  Environment:
    Description: Environment to deploy to.
    Type: String
    Default: test
    AllowedValues:
      - dev
      - test
      - prod

  ServiceName:
    Description: The name of the service
    Type: String
    Default: bi-framework

Resources:

    S3Role:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
                Principal:
                Service:
                - s3.amazonaws.com
                Action:
                - sts:AssumeRole

    SNSRole:
        Type: AWS::IAM::Role
            Properties:
            RoleName: !If [ShouldNotCreateEnvResources, 'quickn9506fafe_sns-role', !Join ['',['quickn9506fafe_sns-role', '-', !Ref env]]]
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                - Sid: ""
                    Effect: "Allow"
                    Principal:
                    Service:
                        - sns.amazonaws.com
                    Action:
                        - sts:AssumeRole
            Policies:
                -
                PolicyName: quickn9506fafe-sns-policy
                PolicyDocument:
                    Version: "2012-10-17"
                    Statement:
                    -
                        Effect: "Allow"
                        Action:
                        - "sns:Publish"
                    Resource: "*"

  DataLakeBucket:
    Type: AWS::S3::Bucket
    DependsOn: InternalNotificationsTopic
    Properties:
      BucketName: !Sub ${ServiceName}-data-lake
      NotificationConfiguration:
        TopicConfigurations:
          - Event: s3:ObjectCreated:Put
            Topic: !Ref InternalNotificationsTopic
        - Event: s3:ObjectCreated:Copy
            Topic: !Ref InternalNotificationsTopic
          - Event: s3:ObjectCreated:Post
            Topic: !Ref InternalNotificationsTopic
          - Event: s3:ObjectCreated:CompleteMultipartUpload
            Topic: !Ref InternalNotificationsTopic
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DataLakeBucket
      PolicyDocument:
        Statement:
          -
            Sid: "ABC123"
            Action:
              - "s3:*"
            Effect: Allow
            Resource: !Join ["", ["arn:aws:s3:::", !Ref DataLakeBucket, "/*"]]
            Principal:
              AWS:
                - !GetAtt S3Role.Arn
