AWSTemplateFormatVersion: '2010-09-09'

Description: Business Intelligence persistence infrastructure

Parameters:

  Environment:
    Description: Environment to deploy to.
    Type: String
    Default: test
    AllowedValues:
      - dev
      - test
      - prod

  ServiceName:
    Description: The name of the service
    Type: String
    Default: bi-framework

Resources:


    S3Notifications:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: s3-notifications

    Subscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        TopicArn: !Ref S3Notifications
        Endpoint: !GetAtt Queue.Arn

    Queue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: bucket-notification-queue
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
          maxReceiveCount: 3

    DeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: bucket-notification-dead-letters

    # LambdaInvokePermission:
    #   Type: AWS::Lambda::Permission
    #   Properties:
    #     FunctionName: !GetAtt DBInsert.Arn
    #     Action: lambda:InvokeFunction
    #     Principal: events.amazonaws.com
    #     SourceArn: !Sub arn:aws:sqs:eu-west-1:${AWS::AccountId}:bucket-notification-queue

    #DBInsertEventSourceMapping:
    #  Type: AWS::Lambda::EventSourceMapping
    #  Properties:
    #    BatchSize: 2
    #    Enabled: true
    #    EventSourceArn: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:bucket-notification-queue
    #    FunctionName: !GetAtt DBInsert.Arn

    SNSTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Id: TopicPolicy
          Version: '2012-10-17'
          Statement:
          - Sid: Statement-id
            Effect: Allow
            Principal:
              AWS: "*"
            Action: sns:Publish
            Resource:
              Ref: S3Notifications
        Topics:
          - Ref: S3Notifications


    QueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Id: QueuePolicy
          Version: '2012-10-17'
          Statement:
            - Sid: Allow-Subscription
              Effect: Allow
              Principal:
                AWS: "*"
              Action: sqs:*
              Resource: !GetAtt Queue.Arn
        Queues:
          - !Ref Queue
